services:
  - type: web
    name: algobuddy-backend
    env: docker
    region: singapore # Feel free to change to ohio, frankfurt, or oregon based on your preference
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      # You will need to securely provide the values for these in the Render Dashboard:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
