spring:
  application:
    name: backend

  datasource:
    # IMPORTANT: If your local wifi does not support IPv6, change "db.uidxqhhepwibwfhfgdsl.supabase.co:5432" 
    # to the "Session Pooler" connection string from your Supabase dashboard!
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.uidxqhhepwibwfhfgdsl
    password: z5y7jUxloyXBgb89
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

supabase:
  jwt:
    secret: "c5cd5e93-47a8-416e-9c8c-be43d82adb08"

server:
  port: 8080
